<center><h1>Merge<center><h1>

---
### Aims for this notebook: 
* [X] Merge Permit_df and Education_df on census tract number
* [X] Final Cleaning of any null values as a result of the merge
    * [ ] Investigate where the nulls are coming from
* [X] CSV Export for **Initial EDA**

In [9]:
import pandas as pd
import numpy as np

import re

***
Functions def

In [10]:
def sel_col(df,reg_exp):
    '''
    This function return a filtered dataframe that contains given (reg_exp) in the column name
    Census_Tract is set as index
    '''
    df['Census_Tract']=df['Census_Tract'].astype('int32')
    temp_df=df.set_index('Census_Tract',drop=True)
    new_df=temp_df.loc[:,[bool(re.search(reg_exp,col)) for col in temp_df]]
    
    return new_df

In [1]:
def preview (df):
    '''
    This formula return basic EDA analysis for the input dataframe in the form of a new dataframe
    '''
    print(f'The dataframe shape is {df.shape}')
    preview_df=pd.DataFrame({'Data Types':df.dtypes,'Total Null Values':df.isna().sum(), 'Null Values Percentage':df.isna().sum()*100/df.shape[0],'Sample Value Head':df.head(1).T.iloc[:,0], 'Sample Value Tail':df.tail(1).T.iloc[:,0],'Sample Value':df.sample().T.iloc[:,0]})
    preview_df.rename_axis('Column_Name',inplace=True)
    return preview_df

***
Load Data

In [11]:
edu_df=pd.read_csv('../data/interim/edu_earnings.csv',index_col=0)
permit_df=pd.read_csv('../data/interim/permits_cleaned.csv',index_col=0)

In [118]:
preview(edu_df)=pd.read_csv('../data/interim/edu_earnings.csv',index_col=0)

The dataframe shape is (804, 13)

,Data Types,Total Null Values,Null Values Percentage,Sample Value Head,Sample Value Tail
Column_Name,,,,,
Census_Tract,int64,0,0.000000,10100.0,980100.0
Median_earnings_2021,float64,8,0.995025,43829.0,NaN
Median_earnings_2020,float64,7,0.870647,41424.0,NaN
Median_earnings_2019,float64,10,1.243781,35985.0,NaN
Median_earnings_2018,float64,10,1.243781,38076.0,NaN
Median_earnings_2017,float64,10,1.243781,36985.0,NaN
Median_earnings_2016,float64,10,1.243781,31107.0,NaN
Median_earnings_2015,float64,10,1.243781,30641.0,NaN
Median_earnings_2014,float64,10,1.243781,30175.0,NaN
Median_earnings_2013,float64,10,1.243781,30795.0,NaN
Median_earnings_2012,float64,10,1.243781,30455.0,NaN
Median_earnings_2011,float64,10,1.243781,31860.0,NaN
Median_earnings_2010,float64,11,1.368159,32631.0,NaN

In [119]:
preview(permit_df)

The dataframe shape is (730511, 24)

,Data Types,Total Null Values,Null Values Percentage,Sample Value Head,Sample Value Tail
Column_Name,,,,,
ID,int64,0,0.0,1614287,3308675
PERMIT_TYPE,object,0,0.0,RENOVATION/ALTERATION,ELECTRIC WIRING
REVIEW_TYPE,object,0,0.0,STANDARD PLAN REVIEW,EASY PERMIT WEB
ISSUE_DATE,object,0,0.0,2006-01-03,2023-02-24
PROCESSING_TIME,float64,0,0.0,81.0,0.0
WORK_DESCRIPTION,object,0,0.0,INTERIOR REMODELING OF EXISTING 3 D.U. PER PLA...,REPAIR SERVICE
BUILDING_FEE_PAID,float64,0,0.0,125.0,75.0
ZONING_FEE_PAID,float64,0,0.0,75.0,0.0
OTHER_FEE_PAID,float64,0,0.0,0.0,0.0
SUBTOTAL_PAID,float64,0,0.0,200.0,75.0
BUILDING_FEE_UNPAID,float64,0,0.0,0.0,0.0
ZONING_FEE_UNPAID,float64,0,0.0,0.0,0.0
OTHER_FEE_UNPAID,float64,0,0.0,0.0,0.0
SUBTOTAL_UNPAID,float64,0,0.0,0.0,0.0
BUILDING_FEE_WAIVED,float64,0,0.0,0.0,0.0
ZONING_FEE_WAIVED,float64,0,0.0,0.0,0.0
OTHER_FEE_WAIVED,float64,0,0.0,0.0,0.0
SUBTOTAL_WAIVED,float64,0,0.0,0.0,0.0
TOTAL_FEE,float64,0,0.0,200.0,75.0
CONTACT_1_TYPE,object,0,0.0,OWNER AS GENERAL CONTRACTOR,CONTRACTOR-ELECTRICAL
CONTACT_1_CITY,object,0,0.0,CHICAGO,SOMERSET
CONTACT_1_STATE,object,0,0.0,IL,NJ
REPORTED_COST,float64,0,0.0,3000.0,500.0
CENSUS_TRACT,int64,0,0.0,220702,530503

In [120]:
permit_df=permit_df.rename(columns={'CENSUS_TRACT':'Census_Tract'})
#drop=permit_df.isna().sum().sort_values(ascending=False).index[permit_df.isna().sum().sort_values(ascending=False)>1300]

***
<Center><h2>MERGE<Center><h2>

In [139]:
#Merge on Census_Tract
df_merged=pd.merge(permit_df,edu_df.iloc[:,::-1],how='inner',on='Census_Tract')

In [140]:
preview(df_merged)

The dataframe shape is (711837, 36)

,Data Types,Total Null Values,Null Values Percentage,Sample Value Head,Sample Value Tail
Column_Name,,,,,
ID,int64,0,0.000000,1614287,1857996
PERMIT_TYPE,object,0,0.000000,RENOVATION/ALTERATION,ELECTRIC WIRING
REVIEW_TYPE,object,0,0.000000,STANDARD PLAN REVIEW,EASY PERMIT WEB
ISSUE_DATE,object,0,0.000000,2006-01-03,2007-10-23
PROCESSING_TIME,float64,0,0.000000,81.0,6.0
WORK_DESCRIPTION,object,0,0.000000,INTERIOR REMODELING OF EXISTING 3 D.U. PER PLA...,INSTALLATION OF (1) 30 AMP DUAL POLE BREAKER A...
BUILDING_FEE_PAID,float64,0,0.000000,125.0,40.0
ZONING_FEE_PAID,float64,0,0.000000,75.0,0.0
OTHER_FEE_PAID,float64,0,0.000000,0.0,0.0
SUBTOTAL_PAID,float64,0,0.000000,200.0,40.0
BUILDING_FEE_UNPAID,float64,0,0.000000,0.0,0.0
ZONING_FEE_UNPAID,float64,0,0.000000,0.0,0.0
OTHER_FEE_UNPAID,float64,0,0.000000,0.0,0.0
SUBTOTAL_UNPAID,float64,0,0.000000,0.0,0.0
BUILDING_FEE_WAIVED,float64,0,0.000000,0.0,0.0
ZONING_FEE_WAIVED,float64,0,0.000000,0.0,0.0
OTHER_FEE_WAIVED,float64,0,0.000000,0.0,0.0
SUBTOTAL_WAIVED,float64,0,0.000000,0.0,0.0
TOTAL_FEE,float64,0,0.000000,200.0,40.0
CONTACT_1_TYPE,object,0,0.000000,OWNER AS GENERAL CONTRACTOR,CONTRACTOR-ELECTRICAL
CONTACT_1_CITY,object,0,0.000000,CHICAGO,CHICAGO
CONTACT_1_STATE,object,0,0.000000,IL,IL
REPORTED_COST,float64,0,0.000000,3000.0,500.0
Census_Tract,int64,0,0.000000,220702,813801
Median_earnings_2010,float64,6557,0.921138,30200.0,27786.0
Median_earnings_2011,float64,6284,0.882786,30096.0,27701.0
Median_earnings_2012,float64,6284,0.882786,25903.0,19989.0
Median_earnings_2013,float64,6284,0.882786,26240.0,22500.0
Median_earnings_2014,float64,6284,0.882786,24821.0,21927.0
Median_earnings_2015,float64,6284,0.882786,27804.0,22473.0
Median_earnings_2016,float64,6284,0.882786,30787.0,23019.0
Median_earnings_2017,float64,6284,0.882786,33905.0,25727.0
Median_earnings_2018,float64,6284,0.882786,36677.0,27572.0
Median_earnings_2019,float64,6284,0.882786,38708.0,31239.0
Median_earnings_2020,float64,4041,0.567686,42926.0,36399.0
Median_earnings_2021,float64,4397,0.617698,44430.0,31691.0

In [141]:
#There are still some missing values. Let's drop census tracts that do not have 
df_merged_clean=df_merged[~(np.isnan(df_merged['Median_earnings_2010'])|np.isnan(df_merged['Median_earnings_2020'])|np.isnan(df_merged['Median_earnings_2021']))]

* [ ] Investigate where the nulls are coming from

In [142]:
#df_merged[df_merged['Median_earnings_2010'].isna()].groupby('Census_Tract').mean()

In [143]:
preview(df_merged_clean)

The dataframe shape is (702310, 36)

,Data Types,Total Null Values,Null Values Percentage,Sample Value Head,Sample Value Tail
Column_Name,,,,,
ID,int64,0,0.0,1614287,1857996
PERMIT_TYPE,object,0,0.0,RENOVATION/ALTERATION,ELECTRIC WIRING
REVIEW_TYPE,object,0,0.0,STANDARD PLAN REVIEW,EASY PERMIT WEB
ISSUE_DATE,object,0,0.0,2006-01-03,2007-10-23
PROCESSING_TIME,float64,0,0.0,81.0,6.0
WORK_DESCRIPTION,object,0,0.0,INTERIOR REMODELING OF EXISTING 3 D.U. PER PLA...,INSTALLATION OF (1) 30 AMP DUAL POLE BREAKER A...
BUILDING_FEE_PAID,float64,0,0.0,125.0,40.0
ZONING_FEE_PAID,float64,0,0.0,75.0,0.0
OTHER_FEE_PAID,float64,0,0.0,0.0,0.0
SUBTOTAL_PAID,float64,0,0.0,200.0,40.0
BUILDING_FEE_UNPAID,float64,0,0.0,0.0,0.0
ZONING_FEE_UNPAID,float64,0,0.0,0.0,0.0
OTHER_FEE_UNPAID,float64,0,0.0,0.0,0.0
SUBTOTAL_UNPAID,float64,0,0.0,0.0,0.0
BUILDING_FEE_WAIVED,float64,0,0.0,0.0,0.0
ZONING_FEE_WAIVED,float64,0,0.0,0.0,0.0
OTHER_FEE_WAIVED,float64,0,0.0,0.0,0.0
SUBTOTAL_WAIVED,float64,0,0.0,0.0,0.0
TOTAL_FEE,float64,0,0.0,200.0,40.0
CONTACT_1_TYPE,object,0,0.0,OWNER AS GENERAL CONTRACTOR,CONTRACTOR-ELECTRICAL
CONTACT_1_CITY,object,0,0.0,CHICAGO,CHICAGO
CONTACT_1_STATE,object,0,0.0,IL,IL
REPORTED_COST,float64,0,0.0,3000.0,500.0
Census_Tract,int64,0,0.0,220702,813801
Median_earnings_2010,float64,0,0.0,30200.0,27786.0
Median_earnings_2011,float64,0,0.0,30096.0,27701.0
Median_earnings_2012,float64,0,0.0,25903.0,19989.0
Median_earnings_2013,float64,0,0.0,26240.0,22500.0
Median_earnings_2014,float64,0,0.0,24821.0,21927.0
Median_earnings_2015,float64,0,0.0,27804.0,22473.0
Median_earnings_2016,float64,0,0.0,30787.0,23019.0
Median_earnings_2017,float64,0,0.0,33905.0,25727.0
Median_earnings_2018,float64,0,0.0,36677.0,27572.0
Median_earnings_2019,float64,0,0.0,38708.0,31239.0
Median_earnings_2020,float64,0,0.0,42926.0,36399.0
Median_earnings_2021,float64,0,0.0,44430.0,31691.0

----
**CSV Export for Initial EDA**

In [144]:
df_merged_clean.to_csv('../data/interim/df_merged.csv')

***